version: "3.7"
services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.backend
    env_file:
      ./backend/.env
    networks:
      - web_network
      - backend_network
    volumes:
      - web_dist:/app/dist

  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile.web
    env_file:
      ./web/.env
    volumes:
      - web_dist:/app/dist
    networks:
      - web_network

networks:
  web_network:
  backend_network:

volumes:
  web_dist: